function fig = plotACG(fgNunber, tittle, gridSize, position, trialNumber, lag, power, lagImagesc, powerImagesc, job )
    fig = figure(fgNunber);
    fig.Name = sprintf('%s_%i', job, fgNunber);
    sgtitle(tittle)
    fig.Position = [1 1 1000 1600];

    subplot(gridSize, 2, position);
    yyaxis right
    plot(lag, power, 'w')
    ylabel('ACG')
    ylim([-0.6,1])
    hold on
    yyaxis left
    imagesc(lagImagesc, [1:size(powerImagesc, 1)], powerImagesc')

    ylabel('Time(s)')
    xlabel('Lag(ms)')
    xlim([-500,500])
    title(sprintf('Trial %i - %s', trialNumber, job))
    % Aesthetics
    set(gca, ...
        'Box',      'off',...
        'FontName', 'Helvetica',...
        'TickDir',  'out', ...
        'TickLength', [.02 .02],...
        'YGrid',     'on',...
        'GridLineStyle', '-.',...
        'XColor',    [.3 .3 .3],...
        'YColor',    [.3 .3 .3],...
        'LineWidth', 1,...
        'FontSize', 8, ...
        'FontWeight', 'bold',...
        'TitleFontSizeMultiplier', 1.2,...
        'LabelFontSizeMultiplier', 0.8,...
        'XScale', 'linear') 
end