function fig = plotPSD(fgNunber, tittle, gridSize, position, trialNumber, yMz, yWh, x)
    fig = figure(fgNunber);
    sgtitle(tittle)
    fig.Position = [1 1 1000 1600];

    subplot(gridSize, 2, position);
    plot(x, yMz, 'k', x, yWh, 'r')
    xlim([0,12])
    ylim([0, 90000])
    ylabel('Power')
    label1{1} = 'Maze';
    label1{2} = 'Wheel';
%     box off
    legend(label1,'location','northwest')%,'orientation','horizontal')
    legend('boxoff')
%     xlim([-500,500])
    title(sprintf('Trial %i', trialNumber))
    % Aesthetics
    set(gca, ...
        'Box',      'off',...
        'FontName', 'Helvetica',...
        'TickDir',  'out', ...
        'TickLength', [.02 .02],...
        'YGrid',     'on',...
        'GridLineStyle', '-.',...
        'XColor',    [.3 .3 .3],...
        'YColor',    [.3 .3 .3],...
        'LineWidth', 1,...
        'FontSize', 8, ...
        'FontWeight', 'bold',...
        'TitleFontSizeMultiplier', 1.2,...
        'LabelFontSizeMultiplier', 0.8,...
        'XScale', 'linear') 
end