
function plotStatsGroupPPower( leftData, rightData, dt, nData, toTitle, lLabel, rLabel, f, yInf, ySup)
    % Max power
    [maxLeft, idxMz] = max(leftData(dt, :));
    [maxRight, idxWh] = max(rightData(dt, :));
 
    left = maxLeft;
    right = maxRight;
    % Error
    errL = std(left)/sqrt(length(left));
    errR = std(right)/sqrt(length(right));
    
    normFactor = mean([left; right]);
    
    [ht, pt, hr, pr] = calcStats(maxLeft, maxRight, normFactor);
    
    % Plot
    subplot(2,3,nData)
    boxplot([left', right'],'Labels',{lLabel,rLabel})
    hold on
    plot([1,2], [left',right'], '.')
    ylabel('Peak Power');
    xlabel(sprintf('Ttest - H: %.1f P:%.4f RankSum - H: %.1f P:%.4f', ht, pt, hr, pr))
%     ttl = sprintf('%s\n Ttest - H: %.1f P:%.4f RankSum - H: %.1f P:%.4f', toTitle, ht, pt, hr, pr); 
    title(toTitle)
    % Aesthetics
    set(gca, ...
        'Box',      'off',...
        'FontName', 'Helvetica',...
        'TickDir',  'out', ...
        'TickLength', [.02 .02],...
        'YGrid',     'on',...
        'GridLineStyle', '-.',...
        'XColor',    [.3 .3 .3],...
        'YColor',    [.3 .3 .3],...
        'LineWidth', 1,...
        'FontSize', 8, ...
        'FontWeight', 'bold',...
        'TitleFontSizeMultiplier', 1.6,...
        'LabelFontSizeMultiplier', 1.4,...
        'XScale', 'linear') 

end