
function plotStats( leftData, rightData, dt, nData, toTitle, lLabel, rLabel)
    left = sum(leftData(dt, :), 1);
    right = sum(rightData(dt, :), 1);

    % Error
    errL = std(left)/sqrt(size(left,1));
    errR = std(right)/sqrt(size(right,1));
    
    % P-value
%     [maxPowerMz, idxMz] = max(leftData(dt, :));
%     [maxPowerWh, idxWh] = max(rightData(dt, :));
%     normFactor = mean([maxPowerMz; maxPowerWh]);

%     [ht, pt, hr, pr] = calcStats(maxPowerMz, maxPowerWh, normFactor);
    
    % Plot
    subplot(2,3,nData)
    plot([1,2], [left',right'], '.-')
    hold on
    bar(1, mean(left), 'FaceColor', 'none')
    bar(2, mean(right), 'FaceColor', 'none')
    errorbar([1,2], [mean(left), mean(right)], [errL, errR])
    xlim([0.5,2.5]);
    xticklabels({'', lLabel, '', rLabel})
%     title(strcat(toTitle,{'/n'}, sprintf('TStudent: %f RankSum: %f', pr, pt)))
    title(toTitle)
    % Aesthetics
    set(gca, ...
        'Box',      'off',...
        'FontName', 'Helvetica',...
        'TickDir',  'out', ...
        'TickLength', [.02 .02],...
        'YGrid',     'on',...
        'GridLineStyle', '-.',...
        'XColor',    [.3 .3 .3],...
        'YColor',    [.3 .3 .3],...
        'LineWidth', 1,...
        'FontSize', 8, ...
        'FontWeight', 'bold',...
        'TitleFontSizeMultiplier', 1.6,...
        'LabelFontSizeMultiplier', 1.4,...
        'XScale', 'linear') 

end